### ISSUE TITLE
Returned error 403 Forbidden

### ISSUE THREAD

**Issue by JAWEN21** [LeapLabTHU/Segment3D#5]
Hi @star9988rr
Thank you for such excellent and inspiring work, I had some problems replicating the work, and when I ran the training code after I had everything ready, I would report errors. I think it may be about the wandb network or login permission. Is there any relevant solution? Looking forward to your reply!
-----------------------------------------------------------------------
hydra.errors.HydraException: Error calling 'pytorch_lightning.loggers.WandbLogger' : failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
-----------------------------------------------------------------------
![2024-11-21 22-50-20 的屏幕截图](https://github.com/user-attachments/assets/8c02dd71-6675-4c47-8869-1d23c5b0d82d)

**Comment by JAWEN21** [comment]
I realize that I might have to find code for the wandb.init() function to change my access, but I didn't find it in your code

**Comment by JAWEN21** [comment]
When I changed "entity:" in the full_yaml configuration file, the issue seemed to be resolved and I could link to wandb, but I ran into a new problem.
![2024-11-22 11-01-02 的屏幕截图](https://github.com/user-attachments/assets/7fb92319-d345-4132-bd8f-098f49b342d2)

**Comment by JAWEN21** [comment]
> ## Hi @star9988rr
> Thank you for such excellent and inspiring work, I had some problems replicating the work, and when I ran the training code after I had everything ready, I would report errors. I think it may be about the wandb network or login permission. Is there any relevant solution? Looking forward to your reply!
> ## hydra.errors.HydraException: Error calling 'pytorch_lightning.loggers.WandbLogger' : failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
> 
> ![2024-11-21 22-50-20 的屏幕截图](https://private-user-images.githubusercontent.com/189253202/388745581-8c02dd71-6675-4c47-8869-1d23c5b0d82d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjM5NDksIm5iZiI6MTczMjI2MzY0OSwicGF0aCI6Ii8xODkyNTMyMDIvMzg4NzQ1NTgxLThjMDJkZDcxLTY2NzUtNGM0Ny04ODY5LTFkMjNjNWIwZDgyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwODIwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDcxYjQ3NWUwYzRjNmExNWQzZWUxNzc4NDQ0ZjZlOTc2ZDBiOWUxMWY2NTIxYjZmNjE2NWUwNGMwYzk3MzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pCP1esbQdJHP_88I-H2WlJpkmL2dn7f-_dCdE5QgWks)

**Comment by sailor-z** [comment]
Hi,

I also got this error. Have you found a solution?
